name: Ts-Bizcase Ci-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./server/TS-BusinessCase/TS-BusinessCase.sln
    - name: Build
      run: dotnet build ./server/TS-BusinessCase --no-restore
    - name: Test
      run: dotnet test ./server/TS-BusinessCase/TS-BusinessCase.sln --no-build --verbosity normal
